# Author: Nick Benedetti (en.benedetti@pm.me)
# Aug 16, 2022
# Source https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log

name: Learn about variables
on: push
env:
  REPO_LONG: $GITHUB_REPOSITORY
  REPO_SHORT: ${GITHUB_REPOSITORY#*/}
jobs:
  step_playground:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: full set output
        run: set
      - name: env environment info
        run: env
      - name: print workflow env variables
        run: |
          echo "$REPO_LONG"
          echo "$REPO_SHORT"
