# Author: Nick Benedetti (en.benedetti@pm.me)
# Aug 16, 2022
# Source https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log

name: Learn about variables
on: push
env:
  REPO_LONG: $GITHUB_REPOSITORY
  REPO_SHORT: ${GITHUB_REPOSITORY#*/}
jobs:
  step_playground:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: prep environemnt
        run: mkdir -p output
      - name: full set output
        run: |
          set
          set > output/set.txt
      - name: env environment info
        run: |
          env
          env > output/env.txt
      - name: print workflow env variables
        run: |
          echo ${{ github.repository }}
          # echo "${ ${{ github.repository }} #*/}"
          echo "$GITHUB_REPOSITORY"
          echo "${GITHUB_REPOSITORY#*/}"
      - name: archive output
        if: always()
        run: tar czf ./archive.tar.gz output
      - uses: actions/upload-artifact@v3
        with:
          name: archive
          path: archive.tar.gz
